FROM debian:stretch
RUN apt update && apt install -y rpm2cpio cpio curl
ADD https://svl-artifactory.juniper.net/artifactory//cn2-static-dev/cn2/kernels/ubuntu/20.04.1/linux-headers-5.4.0-89-generic_5.4.0-89.100_amd64.deb /tmp/kernel/5.4.0-89/linux-headers-5.4.0-89-generic_5.4.0-89.100_amd64.deb
ADD https://svl-artifactory.juniper.net/artifactory//cn2-static-dev/cn2/kernels/ubuntu/20.04.1/linux-headers-5.4.0-89_5.4.0-89.100_all.deb /tmp/kernel/5.4.0-89/linux-headers-5.4.0-89_5.4.0-89.100_all.deb
RUN dpkg -i /tmp/kernel/5.4.0-89/linux-headers-5.4.0-89-generic_5.4.0-89.100_amd64.deb /tmp/kernel/5.4.0-89/linux-headers-5.4.0-89_5.4.0-89.100_all.deb
RUN echo /usr/src/linux-headers-5.4.0-89-generic > /kernelpath
