FROM debian:stretch
RUN apt update && apt install -y rpm2cpio cpio curl
ADD https://svl-artifactory.juniper.net/artifactory//cn2-static-dev/cn2/kernels/ubuntu/20.04.1/linux-headers-5.4.0-72_5.4.0-72.80_all.deb /tmp/kernel/5.4.0-72/linux-headers-5.4.0-72_5.4.0-72.80_all.deb
ADD https://svl-artifactory.juniper.net/artifactory//cn2-static-dev/cn2/kernels/ubuntu/20.04.1/linux-headers-5.4.0-72-generic_5.4.0-72.80_amd64.deb /tmp/kernel/5.4.0-72/linux-headers-5.4.0-72-generic_5.4.0-72.80_amd64.deb
RUN dpkg -i /tmp/kernel/5.4.0-72/linux-headers-5.4.0-72-generic_5.4.0-72.80_amd64.deb /tmp/kernel/5.4.0-72/linux-headers-5.4.0-72_5.4.0-72.80_all.deb
RUN echo /usr/src/linux-headers-5.4.0-72-generic > /kernelpath
